import type { NextPage } from "next";
import Head from "next/head";
import Header from "./";
import styles from "../styles/Home.module.css";
import { useEffect, useLayoutEffect } from "react";
import Router from "next/router";

const LoginPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default LoginPage;
